#Heavier Weapons Configuration
#Sun Sep 06 23:20:40 MSK 2026
cameraShakeEnabled=true
cameraShakeIntensity=1.0
categoryDurations=dagger\:0,claw\:0,fist\:0,sickle\:0,soul_knife\:0,wand\:0,rapier\:1,sword\:2,cutlass\:2,katana\:2,coral_blade\:2,twin_blade\:2,spear\:2,trident\:2,staff\:2,pickaxe\:2,axe\:3,mace\:3,glaive\:3,scythe\:3,battlestaff\:3,lance\:3,claymore\:4,heavy_axe\:4,double_axe\:4,halberd\:4,hammer\:5,anchor\:5
critBonusTicks=2
criticalStrikeCompat=true
defaultHitstopTicks=2
entityFreezeEnabled=true
hitstopDelayTicks=0
hitstopEnabled=true
